Change 'asyncio.exceptions.TimeoutError' to 'asyncio.TimeoutError'
In Python 3.7, 'asyncio.exceptions.TimeoutError' raises AttributeError
: module 'asyncio' has no attribute 'exceptions', since it's in class
'concurrent.futures._base.TimeoutError'. In Python 3.8 onward, TimeoutError
is in class 'asyncio.exceptions.TimeoutError'. Written as 'asyncio.TimeoutError'
will be acceptable for either version.